INSERT INTO users(name, code, profession, color, city, branch, assigned)
VALUES 
('Kyle Lowry', 'F100', 'Drywall Installer', '#FF6600', 'Brampton', 'Abacus',true),
('DeMar DeRozan', 'F101', 'Drywall Installer', 'yellow', 'Brampton', 'Pillsworth',false),
('Fred Van Vleet', 'F102', 'Drywall Installer', 'green', 'Brampton', 'Abacus',false),
('Jonas Valanciunas', 'F103', 'Drywall Installer', '#333333', 'Bolton', 'Pillsworth',true),
('Chris Bosh', 'F104', 'Drywall Installer', '#FF6600', 'Bolton', 'Abacus',true),
('Marcus Camby', 'F105', 'Runner', 'red', 'Brampton', 'Pillsworth',false),
('Vince Carter', 'F106', 'Runner', 'red', 'Toronto', 'Abacus',true),
('Iron Fist', 'F107', 'Hero', 'yellow', 'Hamilton', 'Pillsworth',false),
('Hawkeye', 'F108', 'Hero', 'black', 'Hamilton', 'Abacus',false),
('Thor', 'F109', 'Hero', 'brown', 'Hamilton', 'Pillsworth',true),
('Wolverine', 'F110', 'Hero', 'yellow', 'Markham', 'Abacus',true),
('Wonder Woman', 'F111', 'Hero', 'red', 'Markham', 'Pillsworth',false),
('Zatara', 'F112', 'Hero', 'black', 'Markham', 'Abacus',true),
('Incredible Hulk', 'F113', 'Hero', 'green', 'Markham', 'Pillsworth',false),
('The Shadow', 'F114', 'Hero', 'black', 'Oakville', 'Abacus',false),
('Ghost Rider', 'F115', 'Hero', 'black', 'Oakville', 'Pillsworth',true),
('Green Arrow', 'F116', 'Hero', 'green', 'Oakville', 'Abacus',true),
('Green Lantern', 'F117', 'Hero', 'green', 'Oakville', 'Pillsworth',false),
('Bat Man', 'F118', 'Hero', 'black', 'Oshwa', 'Abacus',true),
('Black Panther', 'F119', 'Hero', 'black', 'Oshwa', 'Pillsworth',false),
('Elektra', 'F120', 'Hero', 'black', 'Oshwa', 'Abacus',false),
('Doctor Strange', 'F121', 'Hero', 'blue', 'Oshwa', 'Pillsworth',true);

